backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "menu"
    label: "Menü"
    file: "content/menu.yml"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
