backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "menu"
    label: "Menü"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Ürün", name: "title", widget: "string" }
      - { label: "Fiyat", name: "price", widget: "number", value_type: "float" }
      - label: "Kategori"
        name: "category"
        widget: "select"
        options:
          - Kahveler
          - Tatlılar
          - İçecekler
          - Yiyecekler
      - { label: "Aktif mi?", name: "active", widget: "boolean", default: true }
